### ISSUE TITLE
Market data is 4 years out of date

### ISSUE THREAD

**Issue by alistair-marshall** [alistair-marshall/cFIREsim-open#5]
Update market data file to include 2016 to 2019.

Use data from Shiller: http://www.econ.yale.edu/~shiller/data.htm
I am not sure where the gold prices are obtained from.

It would be good to document the data sources and possibly have a method to auto generate it rather than risking human error when calculating future years.

**Comment by AS137430** [comment]
"cpi": https://www.multpl.com/cpi/table/by-year 
 "dividends": 0.0213028,
 "fixed_income": https://www.multpl.com/10-year-treasury-rate/table/by-year 
  "gold": -0.276,
  "growth": 0.22114293,
  "cape": https://www.multpl.com/shiller-pe/table/by-year

and https://github.com/boknows/cFIREsim-open/issues/68

**Comment by iLiviu** [comment]
It seems average daily close prices for the year is used to compute gold growth rate (however it seems growth rate for previous year is calculated, however for equities current year growth is used). 
1793-2015 prices can be found here: https://onlygold.com/gold-prices/historical-gold-prices/
for more recent years (1925-2019): https://www.redlakemuseum.com/gold-prices.html
I also found a human error for gold price in 2012, which makes future years data incorrect. Maybe to avoid human errors, actual prices should be used for both equities and gold instead of growth rate?
